name: Manual AKA CS Plugin Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: JDK 17 kurulumu
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Gradle ile build işlemleri
        run: |
          gradle make makePluginsJson ensureJarCompatibility
