name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build plugin
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Copy artifacts
        run: |
          mkdir -p ./build_artifacts
          cp ./aka_cs/build/*.cs3 ./build_artifacts/
          cp ./aka_cs/build/*.jar ./build_artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aka_cs-plugin-artifacts
          path: ./build_artifacts/
