name: Build

on:
  workflow_dispatch:    # manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Build plugin
        run: gradle :aka_cs:clean :aka_cs:build

      - name: Copy artifacts
        run: |
          mkdir -p ./build_artifacts
          cp ./aka_cs/build/*.cs3 ./build_artifacts/ || true
          cp ./aka_cs/build/*.jar ./build_artifacts/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aka_cs-plugin-artifacts
          path: ./build_artifacts/
