name: Android Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Android ortamı
      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: "34.0.0"
          platform-version: "34"
          ndk-version: "25b"

      # 2. Java kurulumu
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build işlemi
      - name: Run Build
        run: |
          # Namespace kontrolü
          if ! grep -q "namespace" aka_cs/build.gradle.kts; then
            sed -i '/android {/a \    namespace = "com.example.aka_cs"' aka_cs/build.gradle.kts
          fi
          
          ./gradlew :aka_cs:build --stacktrace
