name: Auto Gradle Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. GRADLE WRAPPER SİHİRBAZI
      - name: Magic Gradle Setup
        run: |
          # Gerekli araçları kur
          sudo apt-get update
          sudo apt-get install -y unzip
          
          # Gradle indir ve kur (wrapper oluşturmak için)
          wget https://services.gradle.org/distributions/gradle-8.6-bin.zip
          sudo unzip -d /opt/gradle gradle-8.6-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-8.6/bin
          
          # Proje dizininde wrapper oluştur
          gradle wrapper --gradle-version 8.6 --distribution-type bin
          
          # İzinleri ayarla
          chmod +x gradlew
          ./gradlew --version

      # 2. JAVA & ANDROID ORTAMI
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: "34.0.0"
          platform-version: "34"

      # 3. BUILD İŞLEMİ
      - name: Run Build
        run: |
          # Build öncesi cache kontrolü
          if [ -f "gradle.properties" ]; then
            echo "org.gradle.caching=true" >> gradle.properties
          fi
          
          ./gradlew :aka_cs:clean :aka_cs:build --no-daemon --stacktrace

      # 4. ÇIKTILARI KAYDET (Opsiyonel)
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts
          path: |
            aka_cs/build/outputs/
            aka_cs/build/libs/
