name: Android Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. JAVA VE ANDROID ORTAMI
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: "34.0.0"
          platform-version: "34"
          ndk-version: "25b"

      # 2. GRADLE WRAPPER KURULUMU
      - name: Setup Gradle
        run: |
          gradle wrapper --gradle-version 8.6 --distribution-type bin
          chmod +x gradlew

      # 3. PROJE YAPILANDIRMASI
      - name: Configure project
        run: |
          mkdir -p aka_cs/src/main/kotlin
          
          # build.gradle.kts
          cat > aka_cs/build.gradle.kts << 'EOL'
          plugins {
              id("com.android.library") version "8.3.2"
              id("org.jetbrains.kotlin.android") version "1.9.22"
          }
          
          repositories {
              google()
              mavenCentral()
              maven("https://jitpack.io")
          }
          
          android {
              namespace = "com.example.aka_cs"
              compileSdk = 34
              
              defaultConfig {
                  minSdk = 21
              }
              
              compileOptions {
                  sourceCompatibility = JavaVersion.VERSION_17
                  targetCompatibility = JavaVersion.VERSION_17
              }
              
              kotlinOptions {
                  jvmTarget = "17"
              }
          }
          
          dependencies {
              implementation("com.github.Lagradost:CloudStream-3:4.3.4")
          }
          EOL
          
          # AndroidManifest.xml
          cat > aka_cs/src/main/AndroidManifest.xml << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android" />
          EOL

      # 4. BAĞIMLILIKLARI İNDİR
      - name: Download dependencies
        run: ./gradlew :aka_cs:dependencies

      # 5. BUILD ÇALIŞTIR
      - name: Run Build
        run: |
          ./gradlew :aka_cs:clean
          ./gradlew :aka_cs:build --stacktrace --no-daemon
