name: Android Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. GRADLE WRAPPER KURULUMU
      - name: Setup Gradle Wrapper
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle wrapper --gradle-version 8.6 --distribution-type bin
          chmod +x gradlew
          ./gradlew --version

      # 2. ANDROID ORTAMI
      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: "34.0.0"
          platform-version: "34"
          ndk-version: "25b"

      # 3. JAVA KURULUMU
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4. BUILD.GRADLE.KTS DOSYASI OLUŞTURMA
      - name: Create build.gradle.kts if missing
        run: |
          mkdir -p aka_cs
          if [ ! -f "aka_cs/build.gradle.kts" ]; then
            cat > aka_cs/build.gradle.kts << 'EOL'
            plugins {
                id("com.android.library") version "8.3.2"
                id("org.jetbrains.kotlin.android") version "1.9.22"
            }
            
            android {
                namespace = "com.example.aka_cs"
                compileSdk = 34
                defaultConfig {
                    minSdk = 21
                }
            }
            EOL
          fi

      # 5. NAMESPACE KONTROLÜ
      - name: Ensure namespace exists
        run: |
          if ! grep -q "namespace" aka_cs/build.gradle.kts; then
            sed -i '/android {/a \    namespace = "com.example.aka_cs"' aka_cs/build.gradle.kts
          fi

      # 6. BUILD İŞLEMİ
      - name: Run Build
        run: ./gradlew :aka_cs:build --stacktrace
